### PR TITLE
Support input prompts through editors like vim

### PR DESCRIPTION
**Pull request by PraxTube**
It is very useful to be able to write messages with a proper CLI editor like vim (similar to `git commit`) if you have longer prompts or need to copy paste text or code (pasting text for example does not work with the normal `user_input()`). The implementation of this is not so straightforward however. The current implementation uses a global flag in `io.py`, which is rather bad (but I don't know of a better way to do this, if you have any ideas, I am open to suggestions).

I also tried to implemented using [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) but that went pretty horribly. Using `!editor` as a command is much better, especially because this way you can actually read you conversations with the assistant.

**TO DO**

- [x] Print the inputted message to the chat
- [x] Add the command to the rest of the repo (in help etc.)

### CODE REVIEW

**Comment by efJerryYang** [comment]
Thank you for your great ideas. Previously, when I needed to copy and paste long messages, I had to remove consecutive newline characters in advance with an editor. (for example, replacing "\n\n" with "\n"). Your solution here definitely offers a much more convenient method in such situation. 

I will be keeping track of the progress on the branch in your fork!

**Comment by efJerryYang** [comment]
I have just fixed the problem of the global flag when processing the `!editor` command :wave:

**Comment by efJerryYang** [comment]
I have updated the code and tested them locally, and it works fine and is ready for merging. However, any additional feedback you may have would be appreciated before finalizing the merge. Feel free to try out the changes and share any comments you have :smile:

**Comment by PraxTube** [comment]
Hey, just woke up, will try out your changes now :+1:

**Comment by PraxTube** [comment]
Awesome! Looks really good now. I was also considering using a return from the command function but didn't really know how to implement it haha. Good work :+1: .

I only removed one used function and that's it. On my side, the PR would be ready to be merged.

**Pull request merged**
