### PR TITLE
Feat: improve user input handling by detecting command text

### PR DESCRIPTION
**Pull request by efJerryYang**
This commit improves the user input handling by detecting the command text at the `user_input` function. Previously, the input process did not differentiate between command and regular text, requiring the user to press Enter twice to signal the end of input for both cases. With this update, the command text can be directly parsed and executed with the first Enter key press.

### CODE REVIEW

**Comment by efJerryYang** [comment]
Hi @PraxTube, could you help me review the functionality when you have some free time? I believe there's a great need to check the pull requests before merging them, especially when we haven't implemented the testing part.

**Comment by PraxTube** [comment]
Absolutely, I would love to help. I also really like this addition.

**Comment by efJerryYang** [comment]
Great, I will merge this PR tomorrow morning if nothing goes wrong.

**Comment by PraxTube** [comment]
No objections. The changes look good to me.

**Pull request merged**
