### PR TITLE
Add `black` and `mdformat` to CI

### LINKED ISSUE #7: Use python linter/formatter and CI
I want to propose the usage and implementation of a python linter/formatter (i.e. [black](https://github.com/psf/black)). I think there are only upsides to be had once the initial implementation is complete. It makes the code more consistent and readable.

This would also open the door to use a CI (i.e. Github Actions).

I linted with black on a previous version of the code base and it would only reformat 3 files (with default settings). So the code base is already quite clean and implementing a linter/formatter wouldn't quite a lot of conflicts.

### PR DESCRIPTION
**Pull request by PraxTube**
**MOVED TO #10 **

Closes #7 

This PR adds a python linter and a markdown linter to the CI. I added [black](https://github.com/psf/black) and [mdformat](https://github.com/executablebooks/mdformat). If you want to add something else feel free to suggest something. The CI is also testing if the project can be build, so if there are some problems with the build process the CI will fail.

In order for you to format your files on you local branch run

```
black .
```

and

```
mdformat .
```

Note that this will format **in-place**. If you want to check see if something would be formatted before actually doing anything use the `--check` flag (works for both).

**Reviewer Notes**

Given that all files need to be formatted in order for the CI to pass, I had to run both black and mdformat, which is why there are so many changes. So here are the things that are actually new (that have not changed because of a formatter):

- `.github/workflow/python-app.yml` this contains the github actions instructions
- `requirements.txt` added black and mdformat
- added `.mdformat.toml` which contains settings for mdformat

### CODE REVIEW

**Comment by efJerryYang** [comment]
So many files changed here, and I will need some time to examine them. (Oh I understand now that there are only 3 files actually changed)

One problem is that you seem to try making a pull request with the previous commits you have already submitted in your last pull request. Can you first rebase your original branch with the main branch next time, and that will make the commit history much clearer, and before you do that, make a backup of your current branch to avoid any problem that may lead to data loss.

**Comment by efJerryYang** [comment]
Or I can update your branch by force pushing, but I prefer not to do so. You can first backup your current branch by running:
```sh
git branch tmp-backup
```
Then, by running the rebase commands (and handle the conflicts as well):
```sh
git pull --rebase origin main # if it were on my machine, I am not very sure about the exact commands you should run on your machine. The 'origin' means the repository I own, and the 'main' means the branch you want to rebase yours to
```
Now, it may report with conflicts, something looks like this:
```sh
(venv) jerry@ubuntu-sakenfist:~/Projects/chatgpt-cli$ git pull --rebase origin main
From github.com:efJerryYang/chatgpt-cli
 * branch            main       -> FETCH_HEAD
Auto-merging src/utils/cmd.py
CONFLICT (content): Merge conflict in src/utils/cmd.py
Auto-merging src/utils/io.py
CONFLICT (content): Merge conflict in src/utils/io.py
error: could not apply 016d3f4... feat: add basic input from editor (i.e. vim)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 016d3f4... feat: add basic input from editor (i.e. vim)
```
You can now run `git status` to see current status of the rebase process, and run `git rebase --skip` accordingly.

**Comment by efJerryYang** [comment]
Finally, you should be able to see the updated commits on your branch by running `git log --oneline`, which should be clearer than before without the duplicated (ones you have already submitted in your previous PR) and redundant commits (your merge commits with main branch):
```
1a08d8f (HEAD -> dev-editor) fix: remove build packages from `requirements.txt`
f9d6b5e fix: update `requirements.txt`
cba942a fix: make CI install packages for build
7935f8b feat: add `.mdformat.toml`
f74766a feat: add black and mdformat to CI, github actions
ecb1c11 (origin/main, origin/HEAD, tmp-backup, main) fix: windows support for `readline`, close #6 (v0.1.5 -> v0.1.6)
caf06e4 fix: display compatibility with Windows
301fa47 fix: make intermediate directories if they don't exist
cad2fcf chore: add dependency `pyreadline3` to satisfy windows
f47c274 (tag: v0.1.5) feat: support `!editor` command
...
```
I hope these comments here can help!

**Comment by PraxTube** [comment]
Thanks for the help! Yes the commit history is really cluttered, I will rebase the branch. The problem is that I can't create branches on your repo, I have to use my fork and once you merge my fork into your main branch I have to resync my fork (which means I have to merge your repo, which contains my merged fork, back into my fork). Writing it out like this makes it sound even worse haha.

Unfortunately I can also not create multiple forks. I guess I will have to rebase my fork every time before creating a PR.

**Comment by PraxTube** [comment]
The rebasing didn't quite work. I force pushed in order to reset and have a clean commit history. I will open a new PR.

See #10

**Pull request closed without merging**
